### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yiippee** [tidwall/uhasql#2]
Thanks for your project. When I make, here is the error info:
sqlite/sqlite.c:34112:42: error: ‘mremap’ undeclared here (not in a function); did you mean ‘munmap’?
   { "mremap",       (sqlite3_syscall_ptr)mremap,          0 },
                                          ^~~~~~
                                          munmap
sqlite/sqlite.c: In function ‘unixRemapfile’:
sqlite/sqlite.c:38679:42: error: ‘MREMAP_MAYMOVE’ undeclared (first use in this function)
     pNew = osMremap(pOrig, nReuse, nNew, MREMAP_MAYMOVE);

I use the WSL1.0 and gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
Why I get the errors , do I miss something. Thinks again.

**Comment by tidwall** [comment]
I just pushed a fix to ab41343. Thanks for reporting.

**Comment by tidwall** [comment]
I found another linux related issue. I pushed an additional fix. 
Please running`make clean` after pulling the update.
